#!/bin/bash

# Simple deploy script

TARGET="root@raspi"
DIR=/opt/vitographer
DEST=$TARGET:$DIR

ssh $TARGET "mkdir -p $DIR/logs"

scp conf.yml $DEST

scp bin/vitographer $DEST
ssh $TARGET "chmod 755 $DIR/vitographer"

scp cron/vitographer.cron $TARGET:/etc/cron.d/vitographer

scp logrotate/vcontrold.txt $TARGET:/etc/logrotate.d/vcontrold
scp logrotate/vitographer   .txt $TARGET:/etc/logrotate.d/vitographer
